SELECT * FROM `ARTICLE` ORDER BY DESIGNATION ASC; 

SELECT * FROM `ARTICLE` ORDER BY PRIX DESC; 

SELECT * FROM `ARTICLE` WHERE DESIGNATION LIKE 'boulon%' ORDER BY PRIX ASC; 

SELECT * FROM `ARTICLE` WHERE DESIGNATION LIKE '%sachet%'; 

SELECT * FROM `ARTICLE` WHERE LOWER(DESIGNATION) LIKE LOWER('%sAChet%'); 

SELECT * FROM `ARTICLE` INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID ORDER BY FOURNISSEUR.NOM ASC, ARTICLE.PRIX DESC; 

SELECT * FROM `ARTICLE` INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID WHERE FOURNISSEUR.NOM = 'Dubois & Fils'; 

SELECT SUM(PRIX) FROM `ARTICLE` INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID WHERE FOURNISSEUR.NOM = 'Dubois & Fils'; 

SELECT FOURNISSEUR.NOM, SUM(PRIX) FROM `ARTICLE` INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID GROUP BY FOURNISSEUR.NOM; 

SELECT * FROM `BON` WHERE DATE_CMDE BETWEEN '2019-03-01' AND '2019-04-05:12:00'; 

SELECT * FROM `BON` INNER JOIN COMPO ON BON.ID = COMPO.ID_BON INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID WHERE LOWER(ARTICLE.DESIGNATION) LIKE LOWER('%boulon%'); 

SELECT FOURNISSEUR.NOM, BON.DATE_CMDE, ARTICLE.DESIGNATION FROM `BON` INNER JOIN COMPO ON BON.ID = COMPO.ID_BON INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID WHERE LOWER(ARTICLE.DESIGNATION) LIKE LOWER('%boulon%'); 