UPDATE ARTICLE SET DESIGNATION = LOWER(DESIGNATION) WHERE ID=2;

UPDATE ARTICLE SET DESIGNATION = UPPER(DESIGNATION) WHERE PRIX > 10;

INSERT INTO ARTICLE (REF, DESIGNATION, PRIX, ID_FOU) VALUES ('Z00', 'Clous METAL 50 mm (sachet de 1000)', 13.50, 2);
UPDATE ARTICLE SET PRIX = PRIX * 0.9 WHERE ARTICLE.ID NOT IN (SELECT COMPO.ID_ART FROM COMPO);

UPDATE BON INNER JOIN FOURNISSEUR ON BON.ID_FOU = FOURNISSEUR.ID INNER JOIN COMPO ON BON.ID = COMPO.ID_BON SET QTE = QTE * 2 WHERE FOURNISSEUR.NOM = 'Française d''imports'; 

UPDATE ARTICLE SET DESIGNATION = SUBSTRING(DESIGNATION, 1, POSITION('(' IN DESIGNATION) -1) WHERE POSITION('(' IN DESIGNATION) > 0; 