SET SQL_SAFE_UPDATES = 0;

DELETE FROM COMPO WHERE ID_BON IN ( SELECT BON.ID FROM BON WHERE MONTH(BON.DATE_CMDE) = 4 AND YEAR(BON.DATE_CMDE) = 2019 ); 

DELETE FROM BON WHERE MONTH(DATE_CMDE) = 4 AND YEAR(DATE_CMDE) = 2019; 